PROGRAM=helloworld
REMOVE=@rm -f
PRINT=@echo
build:
	@go build -o bin/$(PROGRAM) main.go
	$(PRINT) successfully build $(PROGRAM) at 'bin'.

clear:
	$(REMOVE) bin/*
	$(PRINT) successfully clear the build workspace.


